### ISSUE TITLE
Milestone 3 TODO

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#123]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

- [x] ✅Done
```
Changes to the previous submission must be clearly visible. Use a
  different background color, change bars in the page margin, or other
  ways to clearly indicate the changes.
```
- [ ] ✅Done
```
The log book gives an overview of the changes (but not the full
  changed content) since the last submission.
```
- [ ] ✅Done
```
The actual changes, new developments, etc are integrated into the
  overall document.
```
- [x] ✅Done
```
All the criteria where the previous submission did not follow the
  guidelines have been improved.
```
- [x] ✅Done
```
Any additions and changes follow the guidelines already established
  for the previous submissions.
```
- [ ] ✅Done
```
Completeness of the other development phases: domain description,
requirements prescription, design, … For example, requirements for all
the features that have been implemented are also documented. All the
terms that are used to formulate the requirements are clearly defined
in a terminology, …
```

**Comment by AlfredoSoto1** [comment]
Este issue es más para que se aseguren de que todo se cumpla dentro de lo que está marcado en el mismo.

**Comment by AlfredoSoto1** [comment]
Recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso.

**Comment by edgaelm** [comment]
Updated terminology according to professor feedback: Terminology
1. Player:
 The exerciser engages with the fitness app for workouts, tracking progress, setting goals, and participating in gamified elements.
2. Workouts: 
Exerciser starts a workout, which is a collection of exercises to be completed in a selected environment like home or gym to complete them.
3. Tracking Progress:
Exerciser has the availability to track how his past workouts went and time spent.
4. Setting Goals:
Exercisers have the availability to select the different types of goal they want to achieve, and provide specific types of workouts for weightlifting like strength training, muscle building,  acquire calisthenics capabilities or achieve cardio improvement, with personalized exercises.
5. Gamified Elements:
Features, rewards, challenges, and interactive elements designed to make the exerciser experience more engaging,  enjoyable and motivated.

6. Exercise:
Exerciser starts performing an exercise, which is timed for duration and cooldown. 
7. Environment:
Exercisers may want to change the location the workouts take place from gym to their home depending on equipment availability or comfort. 
 8. Home:
Exerciser wants to complete the workout at home.
9. Gym:
Exercisers that go to the gym to complete their workouts.
10. Types of Workouts:
Exerciser can choose between different categories or genres of exercises based on their fitness goals and preferences. These exercises are calisthenics, weightlifting, strength training, muscle building, cardiovascular activities.
11. Weightlifting
Exerciser wants exercises that involve lifting weights, these workouts are measured by repetitions completed and timer is to count rest time to continue with the next set, and time to complete workout.
12. Strength Training:
Exerciser wants to lift weights focused mainly in strength gaining, with exercises designed to increase muscle strength, endurance, and power, making an emphasis on progressive overload rather than repetitions completed. 
13. Muscle Building:
Exerciser wants to focus on exercises increasing muscular strength and size. The main goal is to have a complete range of motion, specific set and repetition range, and progressive overload. 

14. Calisthenics:
Exerciser wants to focus on calisthenics to have better body weight for resistance.
15. Cardiovascular Activities:
 Exerciser  wants to focus in cardiovascular activities and aim to improve heart and lung health, these workouts are based on the duration of the exercises itself.
16. Personalized Exercises:
Exerciser gets workouts tailored to their fitness level, goals, and any specific preferences or restrictions they may have.
17. FitXp: 
Exerciser earns experience by completing daily challenges, achievements, and quests that contribute to the leveling system. When the exerciser collects  the amount required to level up he will move to the next level.
18. Rewards:
 Incentives and achievements the exerciser earns for completing workouts, achieving fitness milestones, and participating in challenges. Exercisers earn badges, points, or virtual items.
19. Challenges:
 Exercisers will get into challenges with specific goals, tasks, or competitions to push their limits and achieve fitness objectives.
 20. Motivation:
Exercisers will get incentives,  encouragement and inspiration, to maintain their workout routines, achieve fitness goals and maintain their engagement.
21. Performing an Exercise: 
Exerciser starts, stops, resumes, aborts, or completes an exercise.
22. Timer:
Measures the duration of an exercise. It can be started, stopped, paused, or reset in relation to the exercise being performed.
Exercise and Timer Interaction:
For an exercise to be timed, there is a timer running whenever the exercise is being performed.
Timed Exercises: 
Specific exercises that have a specific duration and are monitored by the timer.
Timer Actions: 
Start, stop, pause, and reset the timer initiated by the exerciser in response to their activity in performing an exercise.
Exercise Completion: 
Exerciser completes an exercise, synchronized with the stopping or pausing of the timer, indicating the end of the exercise duration.
Exercise Interruption:
 Exercisers want to abort or pause an exercise.
Resuming an Exercise: 
Exerciser wants to resume a paused or interrupted exercise, the timer also resumes to continue tracking the total exercise time.
23. Engagement:
    Exerciser has a level of involvement, interaction, and interest to achieve a goal, including their participation in workouts, challenges, and social features.
24. Equipment Availability:
Exercisers have availability of exercise with equipment, such as weights, resistance bands, or specialized machines, to use during their workouts, if no equipment is available the exerciser can train at home or even create exerciser-added workouts.
25. Sets:
Group of completed repetition exerciser has made of a given exercise. Exercise can consist of one set, two sets, or more depending on the intensity that the exerciser wants.
26. Repetitions:
The amount of time you repeat the exercise to achieve a quantity already established. Many of the exercises' repetitions depend on what type of training the exerciser is aiming, more repetitions for cutting and less with more weight for bulking.
27. Exerciser-Added Workout:
Exerciser may want to add a workout because the desired workout may not be in the list or because of equipment availability.
28. Locked Levels Roadmap:
The roadmap is level based where the exerciser unlocks unique challenges or rewards depending on the level that the exerciser is. First appearing locked means that the exerciser has not reached the required level to gain access to that particular part of the roadmap.
29. Player complete a milestone:
After completing the milestone the exerciser will receive a reward for completing the optional task. This compensation will be a bigger amount of FitXp that will boost the exerciser level faster. 
30. Player Level: 
A progress that is rewarded as the exerciser that progresses through the exercises. The completion of any exercise will give FitXp. The accumulation of FitXp will complete the amount or required points to move to the next level increasing the difficulty for the exerciser to have a more challenging experience.

**Comment by edgaelm** [comment]
Updated Rough sketch terminology according to professor feedback: Terminology related to sketch
1. Player:
 The exerciser engages with the fitness app for workouts, tracking progress, setting goals, and participating in gamified elements.
2. Workouts: 
Exerciser starts a workout, which is a collection of exercises to be completed in a selected environment like home or gym to complete them.
3. Tracking Progress:
Exerciser has the availability to track how his past workouts went and time spent.
4. Setting Goals:
Exercisers have the availability to select the different types of goal they want to achieve, and provide specific types of workouts for weightlifting like strength training, muscle building,  acquire calisthenics capabilities or achieve cardio improvement, with personalized exercises.
5. Gamified Elements:
Features, rewards, challenges, and interactive elements designed to make the exerciser experience more engaging,  enjoyable and motivated.

6. Exercise:
Exerciser starts performing an exercise, which is timed for duration and cooldown. 
7. Environment:
Exercisers may want to change the location the workouts take place from gym to their home depending on equipment availability or comfort. 
 8. Home:
Exerciser wants to complete the workout at home.
9. Gym:
Exercisers that go to the gym to complete their workouts.
10. Types of Workouts:
Exerciser can choose between different categories or genres of exercises based on their fitness goals and preferences.
11. Weightlifting
Exerciser wants exercises that involve lifting weights, these workouts are measured by repetitions completed and timer is to count rest time to continue with the next set, and time to complete workout.
12. Strength Training:
Exerciser wants to lift weights focused mainly in strength gaining, with exercises designed to increase muscle strength, endurance, and power, making an emphasis on progressive overload rather than repetitions completed. 
13. Muscle Building:
Exerciser wants to focus on exercises increasing muscular strength and size. The main goal is to have a complete range of motion, specific set and repetition range, and progressive overload. 
14. Calisthenics:
Exerciser wants to focus on calisthenics to have better body weight for resistance.
15. Cardiovascular Activities:
 Exerciser  wants to focus in cardiovascular activities and aim to improve heart and lung health, these workouts are based on the duration of the exercises itself.
16. Personalized Exercises:
Exerciser gets workouts tailored to their fitness level, goals, and any specific preferences or restrictions they may have.

17. Rewards:
  Incentives and achievements the exerciser earns for completing workouts, achieving fitness milestones, and participating in challenges. Exercisers earn badges, points, or virtual items.
18. Challenges:
   Exercisers will get into challenges with specific goals, tasks, or competitions to push their limits and achieve fitness objectives.
 19. Motivation:
Exercisers will get incentives,  encouragement and inspiration, to maintain their workout routines, achieve fitness goals and maintain their engagement.

20. Performing an Exercise: 
Exerciser starts, stops, resumes, aborts, or completes an exercise.

21. Timer:
Measures the duration of an exercise. It can be started, stopped, paused, or reset in relation to the exercise being performed.
Exercise and Timer Interaction:
For an exercise to be timed, there is a timer running whenever the exercise is being performed.
Timed Exercises: 
Specific exercises that have a specific duration and are monitored by the timer.
Timer Actions: 
Start, stop, pause, and reset the timer initiated by the exerciser in response to their activity in performing an exercise.
Exercise Completion: 
Exerciser completes an exercise, synchronized with the stopping or pausing of the timer, indicating the end of the exercise duration.
Exercise Interruption:
 Exercisers want to abort or pause an exercise.
Resuming an Exercise: 
Exerciser wants to resume a paused or interrupted exercise, the timer also resumes to continue tracking the total exercise time.

22. Engagement:
    Exerciser has a level of involvement, interaction, and interest to achieve a goal, including their participation in workouts, challenges, and social features.
23. Equipment Availability:
Exercisers have availability of exercise with equipment, such as weights, resistance bands, or specialized machines, to use during their workouts, if no equipment is available the exerciser can train at home or even create exerciser-added workouts.

24. Exerciser-Added Workout:
Exerciser may want to add a workout because the desired workout may not be in the list or because of equipment availability.

**Comment by edgaelm** [comment]
Updated Rough Sketch according to professor feedback: 
![INTRO A INSO-8 2](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78558623/19eae4bf-ce51-48be-892e-5bc409baafa8)

**Comment by edgaelm** [comment]
Changed as stated by professor from Terminology to Interface Requirements: Workout Page:
The place in the application that gives the exerciser the alternative to choose between four different sets of exercises. The first one is “Full Body From Home” where the app gives three exercises to the exerciser that works all the exercisers body. The second  option is “Arms” that gives the exerciser three exercises working all the arms muscles. For the third option the “Legs” are the focus of the exercises giving three different exercises to the exerciser to work. The last of the options is to create the exerciser their own workout routine with a selection of exercises that the app offers for different muscles around the body.
Start button:
The start button appears in all exercises before the exerciser begins. If the exerciser wants to start working out, the start button needs to be pressed.
Skip button:
The skip button appears when doing an exercise to allow the exerciser to skip the exercise without the need to wait for the timer to stop. The exerciser will not be penalized but will not get any FitXp for skipping the exercise.
Finish Workout button:
The finish workout button is to make the exerciser end the workout before the exerciser is done with the exercise. The exerciser that ends the workout without finishing it will not receive a penalty but will not have the FitXp for the exercise that was not completed.
Pause button:
The pause button will appear after pressing the start button. If the exerciser wants to stop the exercise but not lose the progress the pause button will stop the workout and save the time that was stopped and the exercise.
