### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#20]
# Things To-do
- [x] Create a visual diagram describing the architecture of the database
- [x] Choose the appropriate language to use
- [x] Choose the required tools to start developing (must indicate in diagram)

**Comment by AlfredoSoto1** [comment]
For the diagram you can use state charts
(Info on what are state charts are in the professor's presentation)

**Comment by GregAlexander07** [comment]
Data base design is in progress
For the language chosen as far as back-end is concerned, is python
- Given the different background I chose a language that is easy to pick up 
- Since it has a big community, there will be many libraries for any need we may come across, bit will be focusing on Flask

Flask will be the framework that handles the back-end
-This python library should cover all need required for the API
-Django was considered too, but research suggested that flask is more beginner friendly

 PostgreSQL will be the Database Management System(DBMS) for our Database
 -It could've been any among MySQL, MongoDB, to name a few, but most students will take the database course later on and I thought it may be a good opportunity get familiarized with it.
 -Also, research suggested that a relational modeled database fit the needs for the project 
 
 To avoid having to install PostgreSQL in each individual machine of each member of the team I strongly recommend Docker
 -Setting up a database by copying a PostgreSQL imaged is far simpler, since it would avoid the "it works in my machine and not in others"problem.

**Comment by misaelmercado1** [comment]
Working on idealizing diagram(subject to change requiring the need for it to change.
