### ISSUE TITLE
Merging Milestone 2 with 1

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#89]
# Description
With the feedback from milestone 1 update the existing documentation. You need to be in touch with the devs incharged of a specific part of the documentation that had an update from milestone 1. This is to help the current dev working on milestone 2 to not repeat the same mistakes from milestone 1.

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by YampierFernandez** [comment]
I worked on these fixes:

 The synopsis need to cover aspects of the whole project.The other activities part shouldn’t be its own section but the content should be moved to existing areas where it’s relevant (In other word remove the other activities section and take the points mentioned to other sections).


The other activities part shouldn’t be its own section but the content should be moved to existing areas where it’s relevant (In other word remove the other activities section and take the points mentioned to other sections


The function signatures should not go into a section by themselves: their purpose is to complement the understanding of the domain actions and so they should be there with the description of the domain actions.”

Don’t write “as a user” in user stories, because it’s implied. Specify the type of user.
